# Generated by Django 5.0.3 on 2024-05-19 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuJa', '0003_tablerow_column4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default='0', max_length=100)),
                ('company_name', models.CharField(blank=True, default='ĮMONĖ', max_length=100)),
                ('client_address', models.CharField(blank=True, default='ĮMONĖS ADRESAS', max_length=100)),
                ('company_code', models.CharField(blank=True, default='ĮMONĖS KODAS', max_length=100)),
                ('vat_code', models.CharField(blank=True, default='ĮMONĖS PVM KODAS', max_length=100)),
                ('invoice_date', models.DateField(blank=True, default='2024-05-19', null=True)),
                ('payment_date', models.DateField(blank=True, default='2024-05-19', null=True)),
                ('seller_address', models.CharField(blank=True, default='PARDAVĖJO ADRESAS', max_length=100)),
                ('seller_phone_number', models.CharField(blank=True, default='PARDAVĖJO TEL. NR.', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='BANKAS', max_length=100)),
                ('bank_account', models.CharField(blank=True, default='BANKO SĄSKAITA', max_length=100)),
                ('swift', models.CharField(blank=True, default='SWIFT', max_length=100)),
                ('alternative_payment', models.CharField(blank=True, default='ALTERNATYVUS MOKĖJIMAS', max_length=100)),
                ('alternative_account', models.CharField(blank=True, default='ALTERNATYVI SĄSKAITA', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
