# Generated by Django 5.0.3 on 2024-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuJa', '0004_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='company_code',
        ),
        migrations.AddField(
            model_name='userdata',
            name='client_code',
            field=models.CharField(blank=True, default='KLIENTO ĮMONĖS KODAS', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='client_address',
            field=models.CharField(blank=True, default='KLIENTO ADRESAS', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='vat_code',
            field=models.CharField(blank=True, default='KLIENTO PVM KODAS', max_length=100),
        ),
    ]
