# Generated by Django 5.0.3 on 2024-05-19 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuJa', '0007_rename_comany_code_userdata_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='buyer_code',
            field=models.CharField(blank=True, default='ĮMONĖS KODAS', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='buyer_name',
            field=models.CharField(blank=True, default='ĮMONĖS PAVADINIMAS', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='buyer_pvm_code',
            field=models.CharField(blank=True, default='PVM MOKĖTOJO KODAS', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
