# Generated by Django 5.0.3 on 2024-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuJa', '0008_userdata_buyer_code_userdata_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='invoice_date',
            field=models.CharField(default='2024-05-19', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_date',
            field=models.CharField(default='2024-05-19', max_length=100),
        ),
    ]
