# Generated by Django 5.0.3 on 2024-05-23 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuJa', '0009_alter_userdata_invoice_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='invoice_date',
            field=models.CharField(default='2024-05-23', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_date',
            field=models.CharField(default='2024-05-23', max_length=100),
        ),
        migrations.CreateModel(
            name='WriteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_table_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuJa.usertable')),
                ('write_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuJa.writetable')),
            ],
        ),
    ]
