# Generated by Django 5.0.3 on 2024-05-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuJa', '0010_alter_userdata_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerow',
            name='column5',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='tablerow',
            name='column6',
            field=models.CharField(default='Nėra.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='invoice_date',
            field=models.CharField(default='2024-05-28', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_date',
            field=models.CharField(default='2024-05-28', max_length=100),
        ),
    ]
